# **Prueba \#1**

En la siguiente pureba se evalua de manera EXCLUSIVA lo que se solicita, cualquier otra respuesta adicional a ella será valorada, más no evaluada. Entregue la prueba en un repositorio de github antes de el lunes 7 de agosto a las 23:59:59.



### Nombres grupo:

- Moisés Guerrero
- Melissa Arévalo
- Andrés Licona

## **Ejercicio 1** (50 pts)

Escriba una clase `Pedido` que pueda ser usada para gestionar la información de los pedidos realizados a una pastelería (o carnicería o tienda de ropa o empresa que ud desee). Evite usar módulos como numpy, pandas o cualquier otro.

### **Rubrica**:

1. Generación de la clase que funcione correctamente con al menos 2 métodos y 2 atributos. **30 pts**.
2. Comentarios y  documentación que sirva para quien deba usar la clase. **5 pts**.
3. Pertinencia de la clase en el ámbito, ¿Por qué será útil esta herramienta y cómo ayudará a mejorar el negocio? esta será entregada en una celda de texto. **10 pts**.
4. ¿Cree que se pueda construir una clase hija que ayude al proceso? Si sí constrúyala, sino, argumente por qué en una célda de código. **5 pts**.

In [1]:
class Pedido():
    def __init__(self, numero_pedido: int, cliente: str, direccion: str, lista_productos: list = []):
        """
        Inicializa una instancia de la clase PedidoOnline.
        Parámetros:
        numero_pedido (int): Número único que identifica el pedido.
        cliente (str): Nombre completo del cliente
        direccion (str): Direccion del cliente
        lista_productos (list): Lista de productos en el pedido.
        """
        self.numero_pedido = numero_pedido
        self.cliente = cliente
        self.direccion = direccion
        self.lista_productos = lista_productos

    def agregar_producto(self, producto:str):
        """
        Agrega un nuevo producto al pedido,adicionando el producto al
        atributo lista_productos.

        Parámetros:
        producto (str): Nombre del producto a agregar.
        """
        print(f"Se agregó el producto '{producto}' a la lista de productos")
        self.lista_productos.append(producto)
    def estado_entrega(self):
        """
        Actualiza el estado de entrega del pedido para los posibles
        estados definidos:
         [1] Pendiente de pago
         [2] Pendiente de entrega
         [3] Entregado
        El usuario debe indicar mediante el número el estado correspondiente como input semanas
        """
        print("Indique uno de los siguientes números para asignar estado: ")
        print("""
        [1] Pendiente de pago
        [2] Pendiente de entrega
        [3] Entregado
        """)
        estados = ['Pendiente de pago', 'Pendiente de entrega', 'Entregado']
        status_index = int(input("Ingrese el número asignado al estado del pedido: ")) - 1
        try:
            self.status = estados[status_index]
            print(f"Se asigna el estado {estados[status_index]}")
        except Exception as e:
            print("Ocurrió un error al intentar asignar el estado...")
            raise e

In [2]:
pedido1 = Pedido(
    numero_pedido = 1,
    cliente = "Carlos García",
    direccion = "Calle 25 # 33B - 16",
    lista_productos = ['filete de cerdo', 'pechuga de pollo', 'carne molida']
    )
pedido1.agregar_producto('filete de salmón')
pedido1.estado_entrega()
print(pedido1.lista_productos)
print(pedido1.status)

Se agregó el producto 'filete de salmón' a la lista de productos
Indique uno de los siguientes números para asignar estado: 

        [1] Pendiente de pago
        [2] Pendiente de entrega
        [3] Entregado
        
Ingrese el número asignado al estado del pedido: 2
Se asigna el estado Pendiente de entrega
['filete de cerdo', 'pechuga de pollo', 'carne molida', 'filete de salmón']
Pendiente de entrega


#### 3. Utilidad de la herramienta
**R/** Esta herramienta es muy útil para un negocio como una pastelería, una carnicería, tienda de ropa u otros, porque ayuda a ordenar y asignar estados de los pedidos realizados, así como guardar el listado de productos incluidos dentro del pedido.

#### 4. Clase hija de la clase pedido

**R/** Sí es posible construir una clase hija a partir de la clase "Pedido", por ejemplo si se requiere extender las funcionalidades originales para, por ejemplo, hacer pedidos online.

En tal caso, creamos una clase hija "PedidoOnline" que hereda los atributos y metodos de la clase "Pedido" y agrega atributos para incluir el correo electrónico del cliente y metodos para agregar información como preguntas realizadas por el cliente, puntuación del servicio dada luego de realizada la entrega.

In [3]:
class PedidoOnline(Pedido):
    def __init__(self, numero_pedido: int, cliente: str, direccion: str, email_cliente: str, lista_productos: list = []):
        """
        Inicializa una instancia de la clase PedidoOnline.
        Adicionalmente crea el atributo preguntas como una lista vacía donde se incluirán
        todas las preguntas del cliente y respuestas dadas por el vendedor.
        Parámetros:
        numero_pedido (int): Número único que identifica el pedido.
        cliente (str): Nombre completo del cliente
        direccion (str): Direccion del cliente
        email_cliente (str): Correo electronico del cliente
        lista_productos (list): Lista de productos en el pedido.
        """
        Pedido.__init__(self, numero_pedido, cliente, direccion, lista_productos)
        self.email_cliente = email_cliente
        self.preguntas = []
    def responder_pregunta_cliente(self, pregunta):
        """
        Agrega una pregunta dada por el cliente al sistema para que el vendedor pueda
        dar respuesta en el sistema.
        Parámetros:
        pregunta (str): Cadena de texto con la pregunta realizada por el cliente
        """
        print(f"Pregunta realizada por el cliente: \n '{pregunta}'")
        respuesta = str(input("Responder: \n"))
        self.preguntas.append((pregunta, respuesta))
        return self.preguntas
    def puntuacion_servicio(self, puntuacion: int):
        """
        Asigna una puntuación al servicio prestado entre 1 y 10
        Parámetros:
        puntuacion (int): Valor entero entre 1 y 10
        """
        print(f"Puntuacion dada por el cliente sobre el servicio prestado: {puntuacion}/10")
        if puntuacion in range(1,11):
            self.puntuacion = puntuacion
        else:
            raise Exception(f"La puntuacion suministrada '{puntuacion}' no es valida. Debe ser un número entre 1 y 10")

In [4]:
pedidoOnline1 = PedidoOnline(
    numero_pedido = 2,
    cliente = "Carlos García",
    direccion = "Calle 25 # 33B - 16",
    email_cliente = "carlos.garcia237@gmail.com",
    lista_productos = ['filete de cerdo', 'pechuga de pollo', 'carne molida']
)
preguntas = pedidoOnline1.responder_pregunta_cliente(
    pregunta = "¿Tiene disponibles muslos de pollo para incluir al pedido?"
)
print(preguntas)

pedidoOnline1.agregar_producto("muslos de pollo")
pedidoOnline1.estado_entrega()
print(pedidoOnline1.lista_productos)
pedidoOnline1.puntuacion_servicio(10)

Pregunta realizada por el cliente: 
 '¿Tiene disponibles muslos de pollo para incluir al pedido?'
Responder: 
Si señor, si tenemos disponibles
[('¿Tiene disponibles muslos de pollo para incluir al pedido?', 'Si señor, si tenemos disponibles')]
Se agregó el producto 'muslos de pollo' a la lista de productos
Indique uno de los siguientes números para asignar estado: 

        [1] Pendiente de pago
        [2] Pendiente de entrega
        [3] Entregado
        
Ingrese el número asignado al estado del pedido: 3
Se asigna el estado Entregado
['filete de cerdo', 'pechuga de pollo', 'carne molida', 'muslos de pollo']
Puntuacion dada por el cliente sobre el servicio prestado: 10/10


## **Ejercicio 2** (50 pts)

Realice los siguientes ejercicios con numpy

1. Resolver el siguiente sistema de ecuaciones. **16 pts**

$$
2x + 3y - z + 4w + 5v = 15
$$

$$
x - 2y + 4z - 3w + v = 6
$$

$$
3x + 2y - 3z + 5w - 2v = 11
$$

$$
4x + y - 2z + 3w + 2v = 8
$$

$$
x + y + z + w + v = 7
$$

2. Calcule el valor del número de Euler o constante de Napier $e = 2,71828$ como:

$$e = \sum_i ^{\infty} \frac{1}{n!}$$

  ¿Qué precisión en términos de el número de términos necesita para dar cuenta de los primeros 5 números de la coma decimal? **18 pts**

3. Escriba el polinomio característico de la matriz en una celda de texto, déje registrado en una de código cómo obtuvo los valores característicos.  **16 pts**

$$
\begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}
$$



In [5]:
import numpy as np
from scipy.special import factorial

#### 1. Sistema de ecuaciones

In [6]:
f1 = [2, 3, -1, 4, 5]
f2 = [1, -2, 4, -3, 1]
f3 = [3, 2, -3, 5, -2]
f4 = [4, 1, -2, 3, 2]
f5 = [1, 1, 1, 1, 1]

b = np.array([15, 6, 11 , 8, 7])

matriz = np.array([f1,f2,f3,f4,f5])


def res_ecuation_sistem(matriz,b):
    """
    Función que resuelve un sistema de ecuaciones lineales.

    Parámetros:
    matriz (numpy.ndarray): Una matriz de coeficientes del sistema de ecuaciones.
    b (numpy.ndarray): Un vector de términos independientes.

    Retorna:
    numpy.ndarray: Un vector con las soluciones del sistema.

    Ejemplo:
    >>> matriz = np.array([[2, 3, -1, 4, 5],
                           [1, -2, 4, -3, 1],
                           [3, 2, -3, 5, -2],
                           [4, 1, -2, 3, 2],
                           [1, 1, 1, 1, 1]])
    >>> b = np.array([15, 6, 11, 8, 7])
    >>> res_ecuation_sistem(matriz, b)
    array([-1.67741935, -7.87096774,  5.12903226, 10.        ,  1.41935484])
    """
    R = np.linalg.inv(matriz).dot(b)
    return R

x,y,z,w,v = res_ecuation_sistem(matriz,b)
print(f"x = {x}")
print(f"y = {y}")
print(f"z = {z}")
print(f"w = {w}")
print(f"v = {v}")

x = -1.677419354838709
y = -7.870967741935489
z = 5.129032258064518
w = 10.000000000000004
v = 1.4193548387096788


#### 2. Número de Euler

In [7]:
def calc_euler_value(n):
    """
    Esta función calcula el número de Euler o Constante de Napier como la sumatoria del inverso de los factoriales de 1 a n.
    argumentos:
    n: Int = cantidad de elementos en la sumatoria
    """
    # Crear un arreglo con n valores, empezando en 0
    arr = np.arange(n)
    # Calcular los factoriales de los valores del arreglo
    factoriales = factorial(arr)
    # Sumar el inverso de los factoriales
    valor_e = (np.sum(1/factoriales))
    return valor_e

def determinar_cantidad_elementos(start:int = 1):
    """
    Esta función determina la cantidad de números mínimos para obtener el valor Euler con una precisión de 5 decimales
    """
    # Valor Euler de referencia
    e_value = 2.71828
    # Se itera, a través de un while, hasta obtener la precisión deseada
    while abs(calc_euler_value(start) - e_value) > 0.00001:
        start += 1
    print('La cantidad de términos para llegar a una precisión de valor de {valor_euler} es de {num} términos'.format(valor_euler=e_value, num=start))

determinar_cantidad_elementos()

La cantidad de términos para llegar a una precisión de valor de 2.71828 es de 9 términos


#### 3. Polinomio característico de la matriz

Siendo
$$
A = \begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}
$$

El polinomio característico de la matriz viene dado por:

$$ det(A - \lambda I)=0$$

Por tanto sería:

$$
det \begin{pmatrix}
\begin{pmatrix}
2 & 1 & 1 \\
4 & 3 & 2 \\
1 & 1 & 2 \\
\end{pmatrix}-
\begin{pmatrix}
\lambda & 0 & 0 \\
0 & \lambda & 0 \\
0 & 0 & \lambda \\
\end{pmatrix}
\end{pmatrix}
= det\begin{pmatrix}
2-\lambda & 1 & 1 \\
4 & 3-\lambda & 2 \\
1 & 1 & 2-\lambda \\
\end{pmatrix} = 0
$$

$$
-\lambda^{3}+7\lambda^{2}-9\lambda+3 = 0
$$

Despejando $\lambda$ se obtienen los valores:

$$\lambda_{1} = 1$$
$$\lambda_{2} = 0.55$$
$$\lambda_{3} = 5.45$$

In [8]:
# Usando la funcion np.linalg.eigvals() de numpy se obtiene un array con los valores propios para la matriz M dada

def valores_propios(M):
    """
    Para un array de numpy dado, calcula los valores propios asociados, retornando un arreglo con los valores de lambda.
    Ex:
        In[0]: valores_propios(np.array([[2,1,1], [4,3,2], [1,1,2]]))
        Out[0]: array([5.44948974, 0.55051026, 1.        ])
    """
    eigvals = np.linalg.eigvals(M)
    for index, i in enumerate(eigvals):
        print(f"lambda_{index+1} = {i}")
    return eigvals

A = np.array([[2,1,1],
              [4,3,2],
              [1,1,2]])
valores_propios(A)

lambda_1 = 5.44948974278318
lambda_2 = 0.5505102572168231
lambda_3 = 0.9999999999999993


array([5.44948974, 0.55051026, 1.        ])